### ISSUE TITLE
Feature request: Languages

### ISSUE THREAD

**Issue by nagyrobi** [Limych/ha-snowtire#10]
Please add a way to add translations to this component.

**Comment by Limych** [comment]
It's just a binary sensor.  How do you imagine adding translations?

**Comment by nagyrobi** [comment]
The names. Snowtire, Winter, Summer, these would be nice to appear in my own language, not English.

**Comment by Limych** [comment]
English are not my own language too.
The sensor name — "Snowtire" — is just default value. You are free to set any other sensor name your choose.
The sensor, as I said, is binary. It only returns two options for values: "On" or "Off". We cannot change this.
The values ​​"Winter" and "Summer" are used only within the "tire_type" attribute. This attribute was added only for the convenience of understanding the main status — its value directly depends on the main status.

The most that can make sense is to translate these two words. But I'm not sure if it's worth doing. Since this will interfere with the visualization of the sensor and will violate the principle of separating the main logic of the sensor and visualization for the user.

From our discussion with you, I, however, had the idea that it is possible to change the values ​​of the sensor states from "On" / "Off" to "Winter" / "Summer". Then the attribute will become unnecessary.

**Comment by nagyrobi** [comment]
> You are free to set any other sensor name your choose.

I am aware that I can chance the py files myself but an update would kill that.

**Comment by Limych** [comment]
You misunderstood. The name of the sensor is changed through the settings via the “name” field. You do not need to change the component code for this.

**Comment by nagyrobi** [comment]
Oops sorry I didn't read below the patreon advert.
The ​​"Winter" and "Summer" would be nice to be customizable the same way, though. And having these instead of On/Off would be just great.
